services:
  redis:
    image: redis:6-alpine

  client:
    container_name: react-client
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
     - ./:/app
    env_file:
      - ./client/.env.dev
    command: npm run dev
    network_mode: host

  server:
    container_name: flask-server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: flask run --cert=adhoc
    network_mode: host
    ports:
      - 5000:5000
    env_file:
      - ./server/.env.dev
    depends_on:
      - client

