services:
  redis:
    container_name: redis
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    expose:
      - "6379"

  client:
    container_name: react-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
     - ./:/app
    env_file:
      - ./client/.env.dev
    command: npm run dev

  server:
    container_name: flask-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.dev
    command: flask run --host=0.0.0.0 --port=3000
    depends_on:
      - client
      - redis

