# pull the official docker image
FROM python:3.10-slim

# set work directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY requirements.txt ./

# set env variables
ENV FLASK_APP=run.py
ENV FLASK_ENV=development

# install dependencies
RUN pip install -r requirements.txt

EXPOSE 3000